// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://toimylsurwtismvsxhfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvaW15bHN1cnd0aXNtdnN4aGZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2NDg3NjQsImV4cCI6MjA1MzIyNDc2NH0.VYHMXpHvPuDOaAdcoYLP8J6_vYjSJhD0Hc5HjuPGzW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);